name: gdec

channels:
  - pytorch
  - conda-forge

dependencies:
  - conda-build
  - pip

  # Package dependencies
  - jax
  - jaxlib
  - numpy
  - pytorch
  - scipy
  - scikit-learn

  # Executable dependencies
  - ipykernel
  - matplotlib

  # Development dependencies
  - black
  - flake8
  - flake8-blind-except
  - flake8-builtins
  - flake8-docstrings
  - flake8-mutable
  - hypothesis
  - isort
  - mypy
  - pep8-naming
  - pytest

  - pip:
    - flake8-bugbear
