name: gdec

channels:
  - pytorch
  - conda-forge
  - gpytorch
  - plotly

dependencies:
  - conda-build
  - pip
  - python

  # Package dependencies
  - numpy
  - pytorch
  - gpytorch
  - scipy
  - scikit-learn

  # Executable dependencies
  - colorcet
  - ipykernel
  - ipywidgets
  - matplotlib
  - pandas
  - plotly
  - tqdm

  # Development dependencies
  - black
  - flake8
  - flake8-blind-except
  - flake8-builtins
  - flake8-docstrings
  - flake8-mutable
  - hypothesis
  - isort
  - mypy
  - pep8-naming
  - pytest

  - pip:
    - jax
    - jaxlib
    - flake8-bugbear
