name: Test

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install torch jax jaxlib
        pip install -e .[dev]
    - name: Lint with flake8
      run: |
        flake8 gdec tests
    - name: Lint with mypy
      if: runner.os =! 'Windows'  # For some reason mypy breaks on Windows
      run: |
        mypy gdec tests
    - name: Check imports with isort
      run: |
        isort --quiet --recursive --atomic --diff gdec tests
    - name: Check formatting with black
      run: |
        black --diff --quiet gdec tests
    - name: Run tests
      run: |
        pytest
