name: Test (conda)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        auto-update-conda: true
        auto-activate-base: true
        activate-environment: ""
    - name: Install dependencies
      run: |
        conda install -c cdg4 -c pytorch -c conda-forge gdec black flake8 \
          flake8-blind-except flake8-bugbear flake8-builtins flake8-docstrings \
          flake8-mutable hypothesis isort mypy pep8-naming pytest
    - name: Run tests
      run: |
        pytest
