name: Upload to PyPi

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip build twine
    - name: Build package
      run: |
        python3 -m build
    - name: Upload package
      run: >
        python3 -m twine upload -u __token__
        -p ${{ secrets.PYPI_TOKEN }} dist/*
