name: Upload to Anaconda Cloud

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
    - name: Install dependencies
      run: |
        conda install -y anaconda-client conda-build conda-verify
    - name: Build package
      run: |
        mkdir -p ./build/conda
        conda config --set anaconda_upload yes
        conda build --token ${{ secrets.GDEC_CONDA_TOKEN }} -c pytorch -c conda-forge \
          . --output-folder ./build/conda
